name: pobcrawl_tracker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  qr_code_scanner: 1.0.0
  shared_preferences: ^2.2.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: 6.1.0
  carousel_slider: 4.2.1
  http: 1.1.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  animated_splash_screen: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/splash-img.png
    - assets/images/
    - assets/images/topographic.png
    - assets/images/decor-1.png
    - assets/images/decor-2.png
    - assets/images/decor-3.png
    - assets/images/decor-4.png
    - assets/images/decor-5.png
    - assets/images/decor-6.png
    - assets/images/FAB-img.png
    - assets/images/qr-img.png
    - assets/images/divider-img.png
    - assets/images/scan-your-qr.png
    - assets/images/dashboard-home-indicator.png
    - assets/images/fun-roof-img.png

    # Background Images:
    - assets/images/see-all-ongoing-bg.png
    # Carousel Images:
    # Icons
    - assets/icons/
    - assets/icons/hide-pass-ic.png
    - assets/icons/scan-qr-ic.png
    - assets/icons/time-ic.png
    - assets/icons/loc-ic.png
    - assets/icons/rec-ic.png
